In [30]:
def func_a(x):
    if x==0:
        return 0
    else:
        return x/(2*x+1)

def func_b(x):
    if x==0:
        return 0
    else:
        return (x+1)/(2*x+1)

def func_g(x):
    if x==0:
        return 0
    else:
        return x*(x+1)/(2*x+1)

def func_h(x):
    if x==0:
        return 0
    else:
        return x*(x+1)
    
def func_i(x):
    if x==0:
        return 0
    else:
        return 1/(2*x+1)

def fn_2(x):
    ans = func_b(x-2)*func_b(x-1) - 2*func_b(x-2)*func_i(x-1) - func_h(x-2)*func_i(x-2)*func_i(x-1)
    return ans

def fn(x):
    ans = 2*( func_a(x)*func_i(x-1) -func_b(x)*func_i(x+1) ) - 1*( func_a(x)*func_b(x-1) + func_a(x+1)*func_b(x) ) \
        - 1*func_h(x)*func_i(x)*( func_i(x-1)+func_i(x+1) )
    return ans

def fn2(x):
    ans = func_a(x+2)*func_a(x+1) + 2*func_a(x+2)*func_i(x+1) - func_h(x+2)*func_i(x+2)*func_i(x+1)
    return ans

def fn_all(x):
    ans = fn_2(x+2) + fn(x) + fn2(x-2)
    return ans


## V2.0

In [60]:
import numpy as np
import cmath
import matplotlib.pyplot as plt
from matplotlib.colors import Normalize
from matplotlib import cm



def generate(P,n):
    matrix = np.zeros((n, n))
    if n==1:
        matrix[0][0] = fn_all(1)
        return matrix
    else:
        if n%2==0:
            matrix[n-1][n-1] = fn_all(n)
            matrix[n-1][n-2] = P*func_g(n-1)
        elif n%2==1:
            matrix[n-1][n-1] = fn_all(n)
            matrix[n-1][n-2] = func_a(n-1)


        for i in range(n-1):
            if i%2 == 0:
                for j in range(i-1,i+2):
                    if j == i-1:
                        matrix[i][j] = func_a(i)
                    elif j == i:
                        matrix[i][j] = fn_all(i+1)
                    elif j == i + 1:
                        matrix[i][j] = func_b(i+2)

            if i%2 == 1:
                for j in range(i-1,i+2):
                    if j == i-1:
                        matrix[i][j] = P*func_g(i)
                    elif j == i:
                        matrix[i][j] = fn_all(i+1)
                    elif j == i + 1:
                        matrix[i][j] = -P*func_g(i+2)

        return matrix

def get_eigvals(P,n,s='dont show'):
    matrix=generate(P,n)
    # print(matrix)

    eigvals = [(-i,cmath.sqrt(-i).real,cmath.sqrt(-i).imag) for i in np.linalg.eigvals(matrix)]

    reL=[]
    imL=[]
    for j in eigvals:
        if j[1] >= 0 and j[2] >=0:
            reL.append(j[1])
            imL.append(j[2])
        # if j[1] < j[2]:
        #     print('yes')
    
    if s == 'show':
        print(P)
        print(*list(zip(reL,imL)),sep='\n')
        print('-'*100)

    return reL,imL

def draw(ax,x,y,i,P):
    if i=='n':
        # ax.scatter(x,y,s=10,marker='x')
        ax.scatter(x,y,s=1,c=[cmap(norm(P)) for i in range(len(x))])
    else:
        Color=cm.Accent(i)
        ax.scatter(x,y,'x',color=Color,s=10)



'---------------------------------------------'

# s='show'
# # s='dont show'
# P=-10.7
# Ra=1
# fig,ax=plt.subplots()
# for n in [1,2,3,4]:
#     print(n)
#     x,y = get_eigvals(P,n,s)
#     # print(x,y)
#     draw(ax,x,y,'n')

# ax.set_xlim(0,5)
# ax.set_ylim(0,5)
# ax.plot([0,5],[0,5])
# plt.legend(['n=1','n=2','n=3','n=4'])
# plt.show()

'---------------------------------------------'

# # s='show'
# s='dont show'
# n=30
# fig,ax=plt.subplots(figsize=(5,5),dpi=100)
# # Ra=-40
# cmap = plt.cm.viridis
# mini=-10
# maxi=0
# for P in np.arange(mini,maxi,0.1):
# # for P in [-7.3,-268,-3080,-11495]:
# # for P in range(0,5000,5):
#     # for Ra in range(1,5):
#     norm = Normalize(vmin=mini, vmax=maxi)
#     x,y = get_eigvals(P,n,s)
#     # print(x,y)
#     draw(ax,x,y,'n',P)
#     # plt.show()

# ax.set_xlim(0,3)
# ax.set_ylim(0,3)
# ax.plot([0,5],[0,5])

# # ax.set_xlim(0,25)
# # ax.set_ylim(0,25)
# # ax.plot([0,25],[0,25])



# '---------------------------------------------'

# n=20
# fig,ax=plt.subplots(figsize=(5,5),dpi=100)
# P=-7.4
# x,y = get_eigvals(P,n)
# # print(x,y)
# draw(ax,x,y,'n')
# ax.set_xlim(0,7.5)
# ax.set_ylim(0,7.5)
# ax.plot([0,7.5],[0,7.5])
# plt.show()

# '---------------------------------------------'

P=1
for n in [1,2,3,4,5]:
    ans = generate(P,n)
    print(ans)

[[-0.66666667]]
[[-0.66666667  0.6       ]
 [ 0.66666667 -1.        ]]
[[-0.66666667  0.6         0.        ]
 [ 0.66666667 -1.         -1.71428571]
 [ 0.          0.4        -1.        ]]
[[-0.66666667  0.6         0.          0.        ]
 [ 0.66666667 -1.         -1.71428571  0.        ]
 [ 0.          0.4        -1.          0.55555556]
 [ 0.          0.          1.71428571 -1.        ]]
[[-0.66666667  0.6         0.          0.          0.        ]
 [ 0.66666667 -1.         -1.71428571  0.          0.        ]
 [ 0.          0.4        -1.          0.55555556  0.        ]
 [ 0.          0.          1.71428571 -1.         -2.72727273]
 [ 0.          0.          0.          0.44444444 -1.        ]]


## V1.0(wrong)

In [29]:
import numpy as np
import cmath
import matplotlib.pyplot as plt
from matplotlib import cm



def generate(P,n):
    matrix = np.zeros((n, n))
    if n==1:
        matrix[0][0] = fn(1)
        return matrix
    else:
        matrix[0][1] = func_b(2)
        matrix[1][0] = P*func_g(1)
        matrix[1][1] = fn(2)
        if n==2:    
            return matrix
        if n>2:
            if n%2==0:
                matrix[n-1][n-1] = fn(n)
                matrix[n-1][n-2] = P*func_g(n-1)
                matrix[n-1][n-3] = fn_2(n)
            if n%2==1:
                matrix[n-1][n-1] = fn(n)
                matrix[n-1][n-2] = func_a(n-1)
                matrix[n-1][n-3] = fn_2(n)

            for i in range(n-1):
                if i%2 == 0:
                    for j in range(i-1,i+2):
                        if j == i-1:
                            matrix[i][j] = func_a(i)
                        elif j == i:
                            matrix[i][j] = fn(i+1)
                        elif j == i + 1:
                            matrix[i][j] = func_b(i+2)
                    if i-1 > 0:
                        j=i-2
                        matrix[i][j] = fn_2(i+1)
                    if i+2 <= n-1:
                        j=i+2
                        matrix[i][j] = fn2(i+1)
                if i%2 == 1:
                    for j in range(i-1,i+2):
                        if j == i-1:
                            matrix[i][j] = P*func_g(i)
                        elif j == i:
                            matrix[i][j] = fn(i+1)
                        elif j == i + 1:
                            matrix[i][j] = -P*func_g(i+2)
                    if i-1 > 0:
                        j=i-2
                        matrix[i][j] = fn_2(i+1)
                    if i+2 <= n-1:
                        j=i+2
                        matrix[i][j] = fn2(i+1)

            return matrix

def get_eigvals(P,n,s='dont show'):
    matrix=generate(P,n)
    # print(matrix)

    eigvals = [(-i,cmath.sqrt(-i).real,cmath.sqrt(-i).imag) for i in np.linalg.eigvals(matrix)]

    reL=[]
    imL=[]
    for j in eigvals:
        if j[1] >= 0 and j[2] >=0:
            reL.append(j[1])
            imL.append(j[2])
        # if j[1] < j[2]:
        #     print('yes')
    
    if s == 'show':
        print(P)
        print(*list(zip(reL,imL)),sep='\n')
        print('-'*100)

    return reL,imL

def draw(ax,x,y,i):
    if i=='n':
        # ax.scatter(x,y,s=10,marker='x')
        ax.scatter(x,y,marker='x',s=3)
    else:
        Color=cm.Accent(i)
        ax.scatter(x,y,'x',color=Color,s=10)



'---------------------------------------------'

# # s='show'
# s='dont show'
# n=10
# fig,ax=plt.subplots(figsize=(5,5),dpi=100)
# # Ra=-40
# for P in range(-1000,0,1):
# # for P in [-7.3,-268,-3080,-11495]:
# # for P in range(0,5000,5):
#     # for Ra in range(1,5):
#     x,y = get_eigvals(P,n,s)
#     # print(x,y)
#     draw(ax,x,y,'n')

# ax.set_xlim(0,5)
# ax.set_ylim(0,5)
# ax.plot([0,5],[0,5])

# # ax.set_xlim(0,25)
# # ax.set_ylim(0,25)
# # ax.plot([0,25],[0,25])

# plt.show()

# '---------------------------------------------'

P=1
for n in [1,2,3,4,5]:
    ans = generate(P,n)
    print(ans)

[[-0.66666667]]
[[ 0.          0.6       ]
 [ 0.66666667 -1.        ]]
[[-6.66666667e-01  6.00000000e-01  0.00000000e+00]
 [ 6.66666667e-01 -1.00000000e+00 -1.71428571e+00]
 [-2.77555756e-17  4.00000000e-01 -1.00000000e+00]]
[[-6.66666667e-01  6.00000000e-01  0.00000000e+00  0.00000000e+00]
 [ 6.66666667e-01 -1.00000000e+00 -1.71428571e+00  0.00000000e+00]
 [-2.77555756e-17  4.00000000e-01 -1.00000000e+00  5.55555556e-01]
 [ 0.00000000e+00 -5.55111512e-17  1.71428571e+00 -1.00000000e+00]]
[[-6.66666667e-01  6.00000000e-01  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 6.66666667e-01 -1.00000000e+00 -1.71428571e+00  0.00000000e+00
   0.00000000e+00]
 [-2.77555756e-17  4.00000000e-01 -1.00000000e+00  5.55555556e-01
  -5.55111512e-17]
 [ 0.00000000e+00 -5.55111512e-17  1.71428571e+00 -1.00000000e+00
  -2.72727273e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  4.44444444e-01
  -1.00000000e+00]]
